--PENSER A DELETE SEPAREMENT, AVANT DE INSERT
DELETE FROM LIEN;
DELETE FROM TARIF;
DELETE FROM ATTRACTIONS;
DELETE FROM CLIENTS;
DELETE FROM EMPLOYES;
DELETE FROM HORAIRES;

DROP TABLE Attractions CASCADE CONSTRAINTS ;
DROP TABLE Clients CASCADE CONSTRAINTS ;
DROP TABLE Employes CASCADE CONSTRAINTS ;
DROP TABLE Horaires CASCADE CONSTRAINTS ;
DROP TABLE Tarif CASCADE CONSTRAINTS ;
DROP TABLE Lien CASCADE CONSTRAINTS ;
